### ISSUE TITLE
Add a success message after adding a new vacancy

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/jobs-app#11]
Adding a vacancy.
Sending to the web.
No info on success.

Would be good to have a message written 

- "Success! Thanks for adding a vacancy".

- link: add more

link should return to https://jobs.web3privacy.info/add

**Comment by Barabazs** [comment]
Why do you want to add a link to add more vacancies? 
afaik the user stays on the same page when submitting the form, so it does not seem necessary to add a link. Unless I'm misunderstanding what you mean.

**Comment by Msiusko** [comment]
Not really important to add now a new link - you are right.
If it's easy to add new once submitted.

I will test more & will figure out.
What's important here: a non technical manager can add vacancies - because recruiters, assistants etc curate vacancies publishing online (on a protocol side).
