### ISSUE TITLE
Fix "," category legacy

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/jobs-app#16]
We eliminated "category" within the form while leaving "," displayed.

Need to eliminate "," after each org name. Compare screenshot.
<img width="1021" alt="Screenshot 2024-08-16 at 15 15 01" src="https://github.com/user-attachments/assets/1066b7bc-4dc8-460a-a6df-fa9326e06e1a">

screen: DeFi - before, "," - after

**Comment by Barabazs** [comment]
Do you want to continue displaying the legacy company category for those that already have the value? Or remove it entirely?

**Comment by Msiusko** [comment]
Remove it including ",".
