### ISSUE TITLE
RE: fix filtering (new vacancies on top)

### ISSUE THREAD

**Issue by Barabazs** [web3privacy/jobs-app#3]
I would suggest adding a field to the jobs data for the creation date, then you can simply add it as a column with type `date` and when querying you can add a `orderBy(desc(Opening.created_at))` and the data would be sorted as expected.

Since you have a lot of historical, you could add a default date in the past for these entries.

I can make the necessary changes if you want.

**Comment by vorcigernix** [comment]
Absolutely support this 🚀
