### ISSUE TITLE
Adapt visual identity

### ISSUE THREAD

**Issue by Msiusko** [web3privacy/jobs-app#7]
Current Jobs identity is different from the main one: http://web3privacy.info
More accurate visual lib sync is available here: https://ideas.web3privacy.info

We need to adapt branding:
- change the background color 
- change font etc

Brand repo https://github.com/web3privacy/brand
General brand library on Figma: https://www.figma.com/design/fwUaS88ao4Ijlv3gIDYrQD/Web3Privacy?node-id=2090-3151&t=F0A4Z9q6FRW9FXSw-1

**Comment by Barabazs** [comment]
Ok, doing this now.

**Comment by Barabazs** [comment]
PR #9 is based on the main frontend and not the ideas.web3 because it's not clear where I can find the correct repo. So this might not be ready yet..

**Comment by Msiusko** [comment]
This one (general image) is also a placeholder -> can be substituted by Figma lib images (no specifics now - any will work fine): https://jobs.web3privacy.info/add
